### ISSUE TITLE
After cleaning the input & starting typing from scratch, you see the old translation 

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#10]
(This issue is much easier to discover after fixing #5 !)

Steps:

1. Type "om" in Norwegian
2. clean up the input (in one go)
3. Start typing something (like "kat")

**Expected:** the translation is not shown before you finish your input
**Actual:** See the screenshot: 
![Simulator Screen Shot - iPhone 14 Pro - 2022-12-08 at 16 13 51](https://user-images.githubusercontent.com/1670172/206483018-64163a84-f2b0-454e-8d7e-cf7ff0d52fd7.png)

(It will be gone in 500ms after you start typing, but it's enough to get noticed)

**Comment by ektemfg** [comment]
Hey @ksloginov,

The issue you reported has been resolved, and the changes will be pushed to the repository after they have been reviewed and tested by our team. 
We implemented a function which will reset LiveTranslation widget values when input field is empty.
<img width="419" alt="fixlasttranslation" src="https://user-images.githubusercontent.com/99316570/207756065-a6ee2186-b25b-4814-9b25-f81828884c3f.png">
Thank you again for bringing this to our attention!
Dimitrije
