### ISSUE TITLE
Consider adding support for the Dark Mode 

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#11]
**Feature request:** let's add support for the dark mode

**Expected:** while the phone is running in a dark mode, I expect the Google Translator's UI to be adjusted (dark background, white text, etc.)
**Actual:** Light mode is hardcoded to be used in the app

**Comment by ektemfg** [comment]
Awesome feedback. Indeed! Every app needs dark mode!
Check it out:
Light Mode:
<img width="497" alt="normal" src="https://user-images.githubusercontent.com/99316570/207766455-99eb1ccc-b6ea-4ae1-bc39-3c9c8d5365f7.png">

Dark Mode:
<img width="497" alt="dark" src="https://user-images.githubusercontent.com/99316570/207766470-a042d15b-aecf-4752-8080-b36e90e5b37e.png">

Thnx!
