### ISSUE TITLE
Wrap the content into a ScrollView to make all the elements accessible w/ keyboard on

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#3]
(Very similar to  #1 )

**Actual:** With a software keyboard "On", the translations & recent searches are getting hidden under it.
**Expected:** It can be a good idea to hide the keyboard on scroll. And wrap everything into a scrollable container.

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-08 at 15 45 45](https://user-images.githubusercontent.com/1670172/206476461-871c4d85-1db5-4041-be63-a3f2e5d4bcb8.png)

**Comment by ektemfg** [comment]
Thank you!
We have implemented function to hide the keyboard on scroll and made the UI scrollable. Now the user is able to scroll down if widgets are hidden by the keyboard. By scrolling, the keyboard gets hidden too.
Dimitrije
