### ISSUE TITLE
Switching languages doesn't update the translation

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#4]
Repro-steps:

1. Type text in the text field (f.ex. "Bilen står i et bål"), while Norwegian is chosen as a "From" language and English as a "To language. 
2. Stop typing and see the "The car is in a bonfire" translation
3. Click the drop-down menu in the "To" language & choose Spanish

**Expected:** the translation changes to "El auto está en una hoguera"
**Actual:** the translation remains the same

P.S. Same issue applies also to the "From" language picker.

**Comment by ektemfg** [comment]
Hello @ksloginov,

 I am pleased to inform you that the issues with the LanguageBar widget and the switch language button have been resolved. 
Choosing a new language in the LanguageBar widget now updates the translation as expected, and the switch language button now automatically provides the translation as input, making it easier to translate the translation to a third language. 

We are confident that this fix will improve your experience with our app. After our testers confirm the fix. we will update our repo. 
Thank you for bringing these issues to our attention.
Dimitrije

https://user-images.githubusercontent.com/99316570/207763808-cad14d50-6a79-44b3-b002-6fd1abe9c0c8.mov
