### ISSUE TITLE
Favorite button icon is out of sync with favorite button in recent searches 

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#6]
Steps:

1. Search for something 
2. Click the "Star" button
3. Refresh the recent searches
4. Search for the same translation again

**Expected:** the star is filled (i.e. the translation marked as favorited) both in Recent searches & in the LiveTranslation widget
**Actual:** the translation is not shown as favorited in LiveTranslation

![Simulator Screen Shot - iPhone 14 Pro - 2022-12-08 at 15 58 42](https://user-images.githubusercontent.com/1670172/206480611-d9f67b49-ffc0-465e-94e7-6bfa48a2a447.png)

**Comment by ektemfg** [comment]
Hey @ksloginov!
Thank you.
We have now fixed the issue.

https://user-images.githubusercontent.com/99316570/207765652-42cefe5b-684a-4f3b-b6b2-537ac0348a40.mov


We will update our repo after our test users confirm the fix.
Thank you for your feedback!
