### ISSUE TITLE
Favorite state is not saved in between launches

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#7]
Repro Steps:

1. Translate something f.ex. "car"
2. Add the translation to the favorites
3. Restart the app
4. Search for the same item

**Expected:** The start button is filled (i.e. the item is already in Favorites)
**Actual:** The star button is not filled and you can add the item to Favorites

**Comment by ektemfg** [comment]
https://user-images.githubusercontent.com/99316570/207766057-5f725062-70b9-4489-be90-5675aa422c43.mov

Issue is now fixed. Thanks.
