### ISSUE TITLE
Recent Searches are not stored in between launches

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#8]
Similar to #7  , Recent Searches are not stored in between launches.

**Expected:** The user retains their search results after closing down the app and restarting it
**Actual:** The list resets each app launch.

**Comment by ektemfg** [comment]
Good news, @ksloginov, 
We fixed it!
Before app restart:
<img width="497" alt="before" src="https://user-images.githubusercontent.com/99316570/207764406-31831362-ec1d-4774-a3ec-0a598fed9161.png">
After app restart:
<img width="497" alt="after" src="https://user-images.githubusercontent.com/99316570/207764427-f11ef2d9-c85c-4733-a56f-69e8bf1d4212.png">
Will update repo after internal testing.
Thank you!
