### ISSUE TITLE
Clicking refresh to update the list of favorites is not intuitive enough

### ISSUE THREAD

**Issue by ksloginov** [ektemfg/GoogleTranslat0r#9]
## Expected:
Items are automatically added to the list of recent searches (and their favorite status updates if user clicked on the star button)

## Actual:
You need to click the "Refresh" button to see the changes. Plus, seemingly only favorited translations were added to the list.

**Comment by ektemfg** [comment]
Hey!
We have removed this feature. Now the translationHistory list will update automatically.
Thank you for your feedback.
